### PR TITLE
added maxmindinc/geoipupdate container to self-hosted docker setup

### PR DESCRIPTION
**Pull request by samuel-p**
This allows to automatically setup and update a geoip database.

### CODE REVIEW

**Comment by ukutaht** [comment]
Thanks for the PR!

What happens if one doesn't fill in their MaxMind account details here?

I think it makes sense to include a note about how to use this image to the hosting doc: https://github.com/plausible/analytics/blob/master/HOSTING.md#ip-geolocation

**Comment by samuel-p** [comment]
> What happens if one doesn't fill in their MaxMind account details here?

The container will exit with the following error:

```
ERROR: You must set the environment variables GEOIPUPDATE_ACCOUNT_ID, GEOIPUPDATE_LICENSE_KEY, and GEOIPUPDATE_EDITION_IDS!
```

I also can add some details how to use this image in [`HOSTING.md`](https://github.com/plausible/analytics/blob/master/HOSTING.md#ip-geolocation).

**Comment by tckb** [comment]
I think this is not reasonable, ip geolocation should remain optional. As of now, the docker compose  is usable without any additional external signups. The current change forces users to signup maxmid and agree to their license.  @samuel-p  if you could make this config param optional that’s great !

**Comment by samuel-p** [comment]
As far as I know it is not possible to make a service optional in one `docker-compose.yml` file. Alternatively I could move the whole setup for that container and according config to `HOSTING.md` or create a separate `docker-compose-geoip.yml` which contains the setup including geoip, as an alternative to the default `docker-compose.yml`.

**Comment by ukutaht** [comment]
Yeah I think the geoip container should be optional and things should work by default if you don't have Maxmind credentials at hand.

Just a random thought, it could be nice in the future to build a downloader/updater for the database into the web server itself. So we would just need to pass the credentials to the server and it would manage the database itself. 

For now, I like the idea of providing a separate docker-compose file and highlighting it in the `HOSTING.md` doc

**Comment by tckb** [comment]
> it could be nice in the future to build a downloader/updater for the database into the web server itself...

the idea seems good for folks having maxmind's db and also would add value to cloud version.  personally, I would like to move away from Maxminds db as much as possible, I am not a big fan of their  license agreement and their new changes.  I got my 👀  on https://github.com/plausible/analytics/issues/219

**Comment by samuel-p** [comment]
I created the separate `docker-compose-geoip.yml` and reverted the changes in the original `docker-compose.yml`. I also updated the `HOSTING.md` with the new file. Somwhow I messed up when trying to merge the upstream into my changes, but I this it should be fixed now. Can someone please check my changes again and merge them if it all fits so far?

**Comment by ukutaht** [comment]
Looks good to me!

**Pull request merged**
