### PR TITLE
Add `referrers.csv` to CSV export (#2624)

### PR DESCRIPTION
**Pull request by kiote**
### Changes

Added a new file: referrers.csv to statsController. That also required to create a new function in stats controller API (or, maybe I didn't realize how to re-use existing functions). Before only `referrer_drilldown` function was presented, which requires a particular referrer.

### Tests
- [x] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [x] Entry has been added to changelog
- [ ] This PR does not make a user-facing change

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [x] This change does not need a documentation update

### Dark mode
- [ ] The UI has been tested both in dark and light mode
- [x] This PR does not change the UI

### CODE REVIEW

**Comment by ukutaht** [comment]
Thanks @kiote!

I think this PR definitely needs tests to prevent regressions before we can review and approve. We have some existing tests for exported CSVs [here](https://github.com/plausible/analytics/blob/995556e86f7faf420d4c18db6721d532eb1f45f2/test/plausible_web/controllers/stats_controller_test.exs#L154).

**Comment by kiote** [comment]
hey @ukutaht , thanks for checking. What kind of tests you have in mind? currently what I see, there is a check that .zip file with all csv files created, but no test on separate files.. should I create the first one?

**Comment by ukutaht** [comment]
There are a few tests for CSV exports in test/plausible_web/controllers/stats_controller_test.exs

I've enabled CI on this PR and it shows that the existing tests are failing. I think extending the tests that are currently failing would provide good test coverage.

**Comment by kiote** [comment]
Ah, I see. Will look into it, thanks!

**Comment by kiote** [comment]
Hi @ukutaht can you please have a look again? I fixed failing tests, and also got a bit better understanding of the code :muscle:

**Comment by aerosol** [comment]
@kiote hey :wave:, sorry for the delay on that one. If you could rebase your PR I'm going to merge it. We'll also need Browser/OS versions in the export. Is that something you'd be interested in working on? I have some capacity the coming days so I'll be happy to assist.

**Comment by kiote** [comment]
Hey I've made a merge with master, which as I realise afterwards was not exactly the same as rebase you wanted :D 
So what should I do now?

Also would be happy to continue with Browser/OS versions since I have some grasp in it already

**Comment by aerosol** [comment]
> Hey I've made a merge with master, which as I realise afterwards was not exactly the same as rebase you wanted :D
> So what should I do now?

Excellent. thank you!
Same thing effectively, since we squash to master anyway :)

> Also would be happy to continue with Browser/OS versions since I have some grasp in it already

Awesome, looking forward to it!

**Comment by aerosol** [comment]
@kiote something's wrong though: https://github.com/plausible/analytics/actions/runs/5748420928/job/15658447728?pr=3002

**Comment by kiote** [comment]
Looks like the merge didn't go as planned. Sorry for that, will try again soon

**Comment by kiote** [comment]
ok seems like some renaming was made in master, now I followed it too in this PR. Should be better now! Could you please re-try the tests

**Review by aerosol — APPROVED** [review]

**Comment by aerosol** [comment]
Nice, thank you.
Your next PR should kick off CI automatically I hope.

**Pull request merged**
