### PR TITLE
Elixir & Docker upgrade

### PR DESCRIPTION
**Pull request by oliver-kriska**
### Changes
 - upgraded Elixir to 1.11.3
 - upgraded Erlang to 23.2.1
 - upgraded Docker images to use Elixir 1.11.3 and Alpine 3.12.1
 - use [official Elixir Docker Image from HEX](https://hub.docker.com/r/hexpm/elixir) than ["official" from Docker Hub](https://github.com/c0b/docker-elixir)
 - upgraded Phoenix to 1.5.7
 - Upgraded:
  bamboo_postmark 0.6.0 => 0.7.0 (minor)
  bcrypt_elixir 2.2.0 => 2.3.0
  csv 2.3.1 => 2.4.1
  ecto 3.4.6 => 3.5.5
  ecto_sql 3.4.4 => 3.5.3
  elixir_make 0.6.0 => 0.6.2
  ex_machina 2.4.0 => 2.5.0
  excoveralls 0.12.3 => 0.13.4 (minor)
  file_system 0.2.8 => 0.2.10
  gettext 0.18.0 => 0.18.2
  httpoison 1.6.2 => 1.7.0
  nanoid 2.0.2 => 2.0.5
  phoenix_ecto 4.1.0 => 4.2.1
  phoenix_live_reload 1.2.2 => 1.3.0
  postgrex 0.15.5 => 0.15.7
  sentry 7.2.4 => 7.2.5
  timex 3.6.2 => 3.6.3
  tzdata 1.0.3 => 1.0.5
  yamerl 0.8.0 => 0.8.1

### Tests
- [x] This PR does not require tests

### Changelog
- [x] This PR does not make a user-facing change

### Documentation
- [x] This change does not need a documentation update

### CODE REVIEW

**Comment by maco** [comment]
Oh, I'm looking forward to this! I've been running with 1.11 & 23 when doing patches on my laptop because older versions don't compile on Mac OS 11.

**Comment by oliver-kriska** [comment]
@maco  what do you use for installation? ASDF doesn't work too?

**Comment by maco** [comment]
ASDF, yes. The code for old versions don't compile on OS 11 because they have explicit checks for "if 10.11 do this, if 10.12 do this..." and if it's not 10.something then it errors out.

**Comment by ukutaht** [comment]
Thanks @oliver-kriska !

Will test it out locally and on staging today. Once we're on 1.11, I'd also like to use the new `runtime.exs` configuration option to reduce duplication between `config.exs` and `releases.exs`

**Comment by oliver-kriska** [comment]
You are welcome. Yes, it will help to reduce duplicity. I had some issues because of it in my self-hosted instance. But I'm not sure about `runtime.exs` if it can be used also in release (or after release). Let me know when you will do these changes. I can test it too because we use release with all our apps. I think you use mix in production, right?

**Comment by ukutaht** [comment]
> I think you use mix in production, right?

Not sure what you mean, we use the docker image created by `docker build .` in production. Since the build is an elixir release, it does not include the `mix` command.

**Comment by oliver-kriska** [comment]
oh, ok, that's good. 

btw: we use kubernetes and I added another one entrypoint to execute migration with k8s args from deployment.yaml:
```bash
#!/bin/sh
set -e

sleep 10
if echo "$@" | grep 'createdb' ; then
 /entrypoint.sh db createdb
fi
if echo "$@" | grep 'migrate' ; then
  /entrypoint.sh db migrate
fi
if echo "$@" | grep 'init-admin' ; then
  /entrypoint.sh db init-admin
fi

exec /entrypoint.sh run
```
With this you can execute db create and migration before you start app with one command. I don't remember why your solution didn't work for us but this worked.

**Comment by ukutaht** [comment]
I am unable to build a docker container with this setup. See error:

```
➜  analytics git:(pr/566) ✗ docker build -t plausible/analytics:dev .
Sending build context to Docker daemon  698.5MB
Step 1/36 : FROM hexpm/elixir:1.11.3-erlang-23.2.1-alpine-3.12.1 as buildcontainer
1.11.3-erlang-23.2.1-alpine-3.12.1: Pulling from hexpm/elixir
188c0c94c7c5: Already exists 
2a6d6aa4bbd4: Already exists 
d49604d267f0: Pull complete 
4a187a4c5646: Pull complete 
Digest: sha256:e4a75dfb2b5d71d2050fbe6e6947473d060f5e976e3dcc4c4ef8a3d3fb7bfa4e
Status: Downloaded newer image for hexpm/elixir:1.11.3-erlang-23.2.1-alpine-3.12.1
 ---> 177ed2bdaf1c
Step 2/36 : ARG APP_VER=0.0.1
 ---> Running in 2857d3fb4949
Removing intermediate container 2857d3fb4949
 ---> 213404cdaee8
Step 3/36 : ENV MIX_ENV=prod
 ---> Running in b6dc5627308e
Removing intermediate container b6dc5627308e
 ---> 975ccaf44246
Step 4/36 : ENV NODE_ENV=production
 ---> Running in d140baddec2b
Removing intermediate container d140baddec2b
 ---> 43ef10e4b1cb
Step 5/36 : ENV APP_VERSION=$APP_VER
 ---> Running in 18e916329b3d
Removing intermediate container 18e916329b3d
 ---> f0509a680e6a
Step 6/36 : RUN mkdir /app
 ---> Running in 85b7f70055b0
Removing intermediate container 85b7f70055b0
 ---> e543c7c421bf
Step 7/36 : WORKDIR /app
 ---> Running in 5996f0460ae7
Removing intermediate container 5996f0460ae7
 ---> 71806f63dd8a
Step 8/36 : RUN apk add --no-cache git nodejs yarn python npm ca-certificates wget gnupg make erlang gcc libc-dev &&     npm install npm@latest -g &&     npm install -g webpack
 ---> Running in b19dd33a022e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  python (missing):
    required by: world[python]
The command '/bin/sh -c apk add --no-cache git nodejs yarn python npm ca-certificates wget gnupg make erlang gcc libc-dev &&     npm install npm@latest -g &&     npm install -g webpack' returned a non-zero code: 1

```

**Comment by oliver-kriska** [comment]
You have to have python3, I'm not sure why it works for me. Give me a minute.

**Comment by oliver-kriska** [comment]
fixed, sorry
```bash

➜  analytics git:(feature/elixir_upgrade) ✗ docker system prune -a
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all images without at least one container associated to them
  - all build cache

Are you sure you want to continue? [y/N] y
Deleted build cache objects:
fwrerpo7najz9f5qlwhozfwyr
vnqqhb3c18xs426n4ysjueeuf
xxsllyxl9pohoxxc1ycsk664r
zlywo5z0msgo8nb0ydrpdz5ov
jy6rqp2hffm2h0rpa0stu8so5
pdg0n97svq72osppwside9bic
1gb4hkldzeb69doimznj7zo7l
l6njlqiid0g0gc0j7dfc2uck9
gbddpav2qcmicfmelgnmzcya5
waao59ldhtxfyjy1yzn1f8rlx
1bxrx20tplscjsdndq7raauj8
zbqb13w4tv40pt45d4pzq9obe
pbrmtcbivqqome1hccoivek69
nxuiiiu5l7codaieg76wwi2ze
01k9pd2sbszup87jgzsgk0pcf
itgzktcwkl5n1c20zl5fw9evg

Total reclaimed space: 378MB
➜  analytics git:(feature/elixir_upgrade) ✗ docker build . --build-arg APP_VER=1.1.4
[+] Building 395.1s (33/33) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 1.75kB                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/alpine:3.12.1                                                                                                             0.9s
 => [internal] load metadata for docker.io/hexpm/elixir:1.11.3-erlang-23.2.1-alpine-3.12.1                                                                                   1.0s
 => [internal] load build context                                                                                                                                            0.3s
 => => transferring context: 8.78MB                                                                                                                                          0.3s
 => [buildcontainer  1/19] FROM docker.io/hexpm/elixir:1.11.3-erlang-23.2.1-alpine-3.12.1@sha256:e4a75dfb2b5d71d2050fbe6e6947473d060f5e976e3dcc4c4ef8a3d3fb7bfa4e            1.3s
 => => resolve docker.io/hexpm/elixir:1.11.3-erlang-23.2.1-alpine-3.12.1@sha256:e4a75dfb2b5d71d2050fbe6e6947473d060f5e976e3dcc4c4ef8a3d3fb7bfa4e                             0.0s
 => => extracting sha256:188c0c94c7c576fff0792aca7ec73d67a2f7f4cb3a6e53a84559337260b36964                                                                                  394.0s
 => => sha256:2a6d6aa4bbd46eddc0800671c1936bc45a9f9ef9e9867e33715f7ab39d43f6e1 1.59MB / 1.59MB                                                                               0.0s
 => => sha256:d49604d267f061f289ad5a5998cb15ea860f86e90349357185f41e4f2c66fa87 28.88MB / 28.88MB                                                                             0.0s
 => => sha256:4a187a4c56466b887a922f24861bd85101b8f3b66728f031ad0cfddd21434866 4.60MB / 4.60MB                                                                               0.0s
 => => sha256:e4a75dfb2b5d71d2050fbe6e6947473d060f5e976e3dcc4c4ef8a3d3fb7bfa4e 743B / 743B                                                                                   0.0s
 => => sha256:0274cb925787fefdba36ba4a6a12587dcea959858420da662d50aa7d6c0cc105 1.16kB / 1.16kB                                                                               0.0s
 => => sha256:177ed2bdaf1ceedf996ffedd1fbd08001b5cd39baac5ce2362832406e8d13b86 2.40kB / 2.40kB                                                                               0.0s
 => => sha256:188c0c94c7c576fff0792aca7ec73d67a2f7f4cb3a6e53a84559337260b36964 2.80MB / 2.80MB                                                                               0.0s
 => => extracting sha256:2a6d6aa4bbd46eddc0800671c1936bc45a9f9ef9e9867e33715f7ab39d43f6e1                                                                                    0.1s
 => => extracting sha256:d49604d267f061f289ad5a5998cb15ea860f86e90349357185f41e4f2c66fa87                                                                                    0.5s
 => => extracting sha256:4a187a4c56466b887a922f24861bd85101b8f3b66728f031ad0cfddd21434866                                                                                    0.1s
 => [stage-1 1/8] FROM docker.io/library/alpine:3.12.1@sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a                                               0.3s
 => => resolve docker.io/library/alpine:3.12.1@sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a                                                       0.0s
 => => extracting sha256:188c0c94c7c576fff0792aca7ec73d67a2f7f4cb3a6e53a84559337260b36964                                                                                    0.3s
 => => sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a 1.64kB / 1.64kB                                                                               0.0s
 => => sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e 528B / 528B                                                                                   0.0s
 => => sha256:d6e46aa2470df1d32034c6707c8041158b652f38d2a9ae3d7ad7e7532d22ebe0 1.51kB / 1.51kB                                                                               0.0s
 => => sha256:188c0c94c7c576fff0792aca7ec73d67a2f7f4cb3a6e53a84559337260b36964 2.80MB / 2.80MB                                                                               0.0s
 => [stage-1 2/8] RUN apk update && apk upgrade                                                                                                                              2.6s
 => [buildcontainer  2/19] RUN mkdir /app                                                                                                                                    0.3s
 => [buildcontainer  3/19] WORKDIR /app                                                                                                                                      0.0s
 => [buildcontainer  4/19] RUN apk add --no-cache git nodejs yarn python3 npm ca-certificates wget gnupg make erlang gcc libc-dev &&     npm install npm@latest -g &&       77.5s
 => [stage-1 3/8] RUN apk add --no-cache openssl ncurses                                                                                                                     1.8s
 => [stage-1 4/8] COPY .gitlab/build-scripts/docker-entrypoint.sh /entrypoint.sh                                                                                             0.0s
 => [stage-1 5/8] RUN chmod a+x /entrypoint.sh &&     adduser -h /app -u 1000 -s /bin/sh -D plausibleuser                                                                    0.2s
 => [buildcontainer  5/19] COPY mix.exs ./                                                                                                                                   0.0s
 => [buildcontainer  6/19] COPY mix.lock ./                                                                                                                                  0.0s
 => [buildcontainer  7/19] RUN mix local.hex --force &&     mix local.rebar --force &&     mix deps.get --only prod &&     mix deps.compile                                185.7s
 => [buildcontainer  8/19] COPY assets/package.json assets/package-lock.json ./assets/                                                                                       0.1s
 => [buildcontainer  9/19] COPY tracker/package.json tracker/package-lock.json ./tracker/                                                                                    0.0s
 => [buildcontainer 10/19] RUN npm audit fix --prefix ./assets &&     npm install --prefix ./assets &&     npm install --prefix ./tracker                                   50.5s
 => [buildcontainer 11/19] COPY assets ./assets                                                                                                                              0.1s
 => [buildcontainer 12/19] COPY tracker ./tracker                                                                                                                            0.0s
 => [buildcontainer 13/19] COPY config ./config                                                                                                                              0.0s
 => [buildcontainer 14/19] COPY priv ./priv                                                                                                                                  0.1s
 => [buildcontainer 15/19] COPY lib ./lib                                                                                                                                    0.2s
 => [buildcontainer 16/19] RUN npm run deploy --prefix ./assets &&     npm run deploy --prefix ./tracker &&     mix phx.digest priv/static                                  47.3s
 => [buildcontainer 17/19] WORKDIR /app                                                                                                                                      0.0s
 => [buildcontainer 18/19] COPY rel rel                                                                                                                                      0.0s
 => [buildcontainer 19/19] RUN mix release plausible                                                                                                                        21.5s
 => [stage-1 6/8] COPY --from=buildcontainer /app/_build/prod/rel/plausible /app                                                                                             1.0s
 => [stage-1 7/8] RUN chown -R plausibleuser:plausibleuser /app                                                                                                              6.0s
 => [stage-1 8/8] WORKDIR /app                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                       1.5s
 => => exporting layers                                                                                                                                                      1.4s
 => => writing image sha256:81c7a4edd472e8a8b62129ad6674cc44805d1a711e229a76f7e078ecc39cba50
 ```

**Comment by oliver-kriska** [comment]
newer version of alpine linux has package python3 not python

**Comment by ukutaht** [comment]
Thanks!

**Pull request merged**
