### PR TITLE
Update to the copy

### PR DESCRIPTION
**Pull request by metmarkosaric**
Update to the copy to include a note about billable pageviews. hopefully it doesn't make the copy too long...

### CODE REVIEW

**Comment by zoldar** [comment]
Looks ok in desktop view but feels a bit too spread vertically on mobile now?

https://github.com/user-attachments/assets/0e20888d-1eb8-4c0a-a4da-120ed26a3ef2

**Comment by metmarkosaric** [comment]
true @zoldar! any way to make it nicer?

**Comment by zoldar** [comment]
@metmarkosaric It's a bit tricky as the tooltip icon is already a link to the external page. As there's no other way to trigger the tooltip than by touch in this context, it's kind of pointless IMHO. Maybe we should do away with tooltip entirely here for smaller screens?

**Comment by metmarkosaric** [comment]
@zoldar sure, that works

**Review by zoldar — APPROVED** [review]

**Pull request merged**
