### PR TITLE
Add loading state to site cards

### PR DESCRIPTION
**Pull request by aerosol**
### Changes

shows loading state, so that "0 visitors" doesn't flash before ws connects.

cc @ukutaht - if you like to test/tweak locally, add :timer.sleep(3000) after `connected?` on line 498

### CODE REVIEW

**Comment by ukutaht** [comment]
Suggestion: https://github.com/plausible/analytics/commit/6aeea48a8ce83a5992bb90b0f26631ffc824b2b7

**Comment by aerosol** [comment]
@ukutaht I pushed it here, but doesn't look good:


https://github.com/plausible/analytics/assets/173738/9c25b0e8-10e9-497a-9c16-e07a1d477c00

**Comment by aerosol** [comment]
I get the idea though, will fiddle with it

**Comment by aerosol** [comment]
https://github.com/plausible/analytics/assets/173738/bd2627b6-210e-4a0c-b493-fe5f3a78ae35

@ukutaht

**Comment by aerosol** [comment]
Pixel units are not great if we want to keep it responsive...
the best I can do:

https://github.com/plausible/analytics/assets/173738/856921aa-47ce-4277-9fee-48263bdbc442

not super happy about the box padding then

**Comment by aerosol** [comment]
force pushed https://github.com/plausible/analytics/pull/3483/commits/7f9bfa9ca7128ca2c452839e74e81f43ab9cf1ac should make it decent for both mobile/desktop views

**Review by zoldar — APPROVED** [review]
🚀

**Pull request merged**
