### PR TITLE
add support for DATABASE_SEARCH_PATH

### PR DESCRIPTION
**Pull request by ruslandoga**
### Changes

This PR adds support for custom PostgreSQL `search_path` as requested in #3799 

- [x] I'll need to check if this approach is good enough.

### Tests
- [ ] Automated tests have been added

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated

### Dark mode
- [x] This PR does not change the UI

### CODE REVIEW

**Review by aerosol — APPROVED** [review]

**Comment by Nikola-Milovic** [comment]
Any chances this makes it into next release?

**Comment by Nikola-Milovic** [comment]
Any ETA for the release this would be included in?

**Comment by ruslandoga** [comment]
@plausible/developers any advice on how to test this?

**Comment by ruslandoga** [comment]
@Nikola-Milovic could you please verify that the approach in https://github.com/plausible/analytics/discussions/3799#discussioncomment-8569539 worked?

**Comment by Nikola-Milovic** [comment]
@ruslandoga Pretty much working

```console
postgres=# \dn
   List of schemas
   Name    |  Owner
-----------+----------
 plausible | postgres
 public    | postgres
(2 rows)

postgres=# \d
                List of relations
 Schema |       Name       |   Type   |  Owner
--------+------------------+----------+----------
 public | oban_jobs        | table    | postgres
 public | oban_jobs_id_seq | sequence | postgres
 public | oban_peers       | table    | postgres
(3 rows)

postgres=# set schema 'plausible';
SET
postgres=# \d
                          List of relations
  Schema   |               Name                |   Type   |  Owner
-----------+-----------------------------------+----------+----------
 plausible | api_keys                          | table    | postgres
 plausible | api_keys_id_seq                   | sequence | postgres
 plausible | check_stats_emails                | table    | postgres
 plausible | check_stats_emails_id_seq         | sequence | postgres
 plausible | create_site_emails                | table    | postgres
 plausible | create_site_emails_id_seq         | sequence | postgres
 plausible | custom_domains                    | table    | postgres
 plausible | custom_domains_id_seq             | sequence | postgres
 plausible | email_verification_codes          | table    | postgres
 plausible | enterprise_plans                  | table    | postgres
 plausible | enterprise_plans_id_seq           | sequence | postgres
 plausible | feedback_emails                   | table    | postgres
 plausible | feedback_emails_id_seq            | sequence | postgres
 plausible | fun_with_flags_toggles            | table    | postgres
 plausible | fun_with_flags_toggles_id_seq     | sequence | postgres
 plausible | goals                             | table    | postgres
 plausible | goals_id_seq                      | sequence | postgres
 plausible | google_auth                       | table    | postgres
 plausible | google_auth_id_seq                | sequence | postgres
 plausible | intro_emails                      | table    | postgres
 plausible | intro_emails_id_seq               | sequence | postgres
 plausible | invitations                       | table    | postgres
 plausible | invitations_id_seq                | sequence | postgres
 plausible | monthly_reports                   | table    | postgres
 plausible | monthly_reports_id_seq            | sequence | postgres
postgres=# \d
```

The oban library seems to still put its schemas into public


Demo https://github.com/Nikola-Milovic/plausible-schema-demo

`docker compose up` should just work

**Comment by ruslandoga** [comment]
There have been some changes since v2.0.0 that make it harder to support this env var, please see https://github.com/Nikola-Milovic/plausible-schema-demo/pull/1#issue-2284553627

Since the current PR is not going to solve the issue anyway (due to failing migrations), I'm going to close it. Sorry!

**Pull request closed without merging**
