### PR TITLE
update changelog with v2.0.0

### PR DESCRIPTION
**Pull request by ruslandoga**
This PR just updates the changelog.

- [x] pending on https://github.com/plausible/analytics/discussions/3035

### CODE REVIEW

**Comment by FarisZR** [comment]
It looks like V2 was already released? The `latest` tag is already using v2.0.0.

**Comment by ruslandoga** [comment]
👋 @FarisZR 

It was just me being too hasty about creating a tag. `v2.0.0` would probably be published officially next week.

**Comment by ruslandoga** [comment]
To avoid any further problems with self-hosting setups using `latest` tag, I've re-tagged `v1.5.1` to force a CI run to publish `latest` that points to `v1.5.1`.

**Comment by aerosol** [comment]
@ruslandoga shall we merge this?

**Comment by ruslandoga** [comment]
I've marked it as "draft" until https://github.com/plausible/analytics/pull/2970 is merged.

**Comment by aerosol** [comment]
@ruslandoga #2970 merged

**Comment by ruslandoga** [comment]
I'll double check the changelog (and add a line for https://github.com/plausible/analytics/pull/2970) and mark this PR as ready.

**Review by aerosol — APPROVED** [review]

**Pull request merged**
