### PR TITLE
Add webhook alert from Checkly -> Instatus

### PR DESCRIPTION
**Pull request by ukutaht**
### Changes

Adds webhook to notify Instatus when a Checkly health check fails.

### CODE REVIEW

**Review by cnkk — APPROVED** [review]
lgtm!

The terraform plan output is correct. The unrelated change looks like an internal change on their side. This shouldn't change the current behaviour.

**Comment by ukutaht** [comment]
@cnkk the alert channel wasn't actually hooked up to anything. I've tried attaching it to just one of the checks here: https://github.com/plausible/analytics/pull/2840/commits/e7e28ee74c02cef3d50677fb5d071283967e615f

**Comment by aerosol** [comment]
@ukutaht @cnkk doing some minor cleanup with the PRs, just checking if you guys still want this in?

**Comment by cnkk** [comment]
@aerosol we want to switch to instatus.com in the mid-term. I think there are not many steps left.
So, this PR is still relevant.

**Pull request merged**
