### PR TITLE
Migration: Increase the precision of subscription timestamp fields

### PR DESCRIPTION
**Pull request by RobertJoonas**
### Changes

Motivation: Paddle sometimes sends us two webhooks at the same time when a subscription is updated. We only need to count the latest one of those, for which we need more precision than 1s.

The migration will set both `inserted_at` and `updated_at` columns in the `subscriptions` table to use the `:naive_datetime_usec` type instead of just `:naive_datetime`. In practice, we currently need more precision only on the `updated_at` field. But I suppose it's better to keep the type between both timestamp fields consistent.

### Tests
- [x] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog
- [x] This PR does not make a user-facing change

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [x] This change does not need a documentation update

### Dark mode
- [ ] The UI has been tested both in dark and light mode
- [x] This PR does not change the UI

### CODE REVIEW

**Review by zoldar — APPROVED** [review]
Migrated on staging, everything seems to work fine afterwards.

**Comment by ukutaht** [comment]
Can this be closed @RobertJoonas ? If I remember right this was solved some other way?

**Comment by aerosol** [comment]
>  If I remember right this was solved some other way?

What way? I think this might be a lead for https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/7231303811

**Comment by zoldar** [comment]
Yup, finally found it while looking into something else - this particular issue was solved by ignoring particular state update for subscription which always precedes resuming the subscription https://github.com/plausible/analytics/pull/4240

https://github.com/plausible/analytics/blob/master/lib/plausible/billing/billing.ex#L140-L155

We can close this PR for now

**Pull request closed without merging**
