### PR TITLE
Add `utm_content` and `utm_term`.

### PR DESCRIPTION
**Pull request by BlenderDefender**
Support `utm_content` and `utm_term` as requested in #515.

### Changes
I have added support for `utm_content` and `utm_term` and made a separate tab for these parameters. It works as far as I've tested it, but I honestly don't know if I did something wrong, because it's my first time scripting with Elixir. One improvement that could/should be made for this is splitting the `utm_term` across some separator like a comma or a semicolon:
How it looks right now:
image
How it should look:
image

### Tests
- [x] This PR does not require tests

### Changelog
- [x] Entry has been added to the changelog

### Documentation
- [x] [Docs](https://github.com/plausible/docs) have been updated

### CODE REVIEW

**Comment by metmarkosaric** [comment]
> Sounds really interesting. I'm really looking forward to seeing this feature in Plausible. It's funny, I discovered Plausible like a week ago from a random youtube video, and now I'm already contributing a feature lol. I must admit that it was just copying and pasting the code from `utm_campaign` tho, but I think that's fine because it's working.

hehe that's very cool, thanks for the contribution! do you remember what video you discovered Plausible on?

**Comment by BlenderDefender** [comment]
I hope so, but unfortunately, that's up to the developers of Plausible and there's nothing I can do to get this merged faster.

**Comment by ukutaht** [comment]
This is now live on https://plausible.io !

**Comment by metmarkosaric** [comment]
nice! just checked it out, it's missing the dark theme

Screenshot from 2021-12-20 10-18-44

**Comment by BlenderDefender** [comment]
I've noticed two more (minor) things:
1. The "Details" Popup doesn't show for any of the UTM parameters:
grafik
2. You can't filter by UTM Content or UTM Term:
grafik

Thank you for taking a look at this :)

**Comment by metmarkosaric** [comment]
thanks! nr 1 has been fixed and is on our staging currently

**Comment by ukutaht** [comment]
Thanks @BlenderDefender! The details modals are fixed and I've also just added the filters back on master. The modals fix is already live but the filters will be deployed in the next few days

**Pull request closed without merging**
