### PR TITLE
Update react-router to version 6

### PR DESCRIPTION
**Pull request by apata**
### Changes

Redo of https://github.com/plausible/analytics/pull/4384.

It's almost exactly the same as before, except link and navigation search parameters aren't parsed and stringified at the router level, the transforms are applied in custom components. 

* deprecates withRouter HOC
* explicitly declares all app routes
* makes navigating to each route use the route definition
* replaces PlausibleSearchParams with a stringifySearch and parseSearch method, which are applied in the wrapped Link and navigate components AppNavigationLink and useAppNavigate and in QueryContextProvider
  * NB! components are operating with and changing the parsed object
  * NB! setting search param value to false used to be the way to remove the search param, but I wasn't able to keep this behavior, now setting the value to null is the way to do it
* refactors navigation links and buttons to new navigate API

### Tests
- [ ] Automated tests have been added
- [x] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog
- [x] This PR does not make a user-facing change

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [x] This change does not need a documentation update

### Dark mode
- [x] The UI has been tested both in dark and light mode
- [ ] This PR does not change the UI

### CODE REVIEW

**Comment by apata** [comment]
This time, it's tested to work with sites containing a forward slash: https://pr-4408.review.plausible.io/arturplausiblestaging.plausible.io%2Fdeep%2Fpath/?filters=((is,country,(RS)))&labels=(RS:Serbia)

**Review by ukutaht — APPROVED** [review]

**Comment by ukutaht** [comment]
Getting this error on the preview deployment:

Screenshot 2024-07-31 at 13 47 41

**Comment by apata** [comment]
> Getting this error on the preview deployment:
> 
> Screenshot 2024-07-31 at 13 47 41

Ah damn, browser difference in URLSearchParams implementation most likely. Getting the same with Safari. Checking

**Comment by apata** [comment]
Refactored to one of the methods listed in the url search params polyfill library that we use (https://github.com/jerrybendy/url-search-params-polyfill?tab=readme-ov-file#foreach). That should be safer, even though entries should have been compatible (https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/entries#browser_compatibility). Double checking with other browsers as well.

**Pull request merged**
