### PR TITLE
feature/manage-goals-api-routes

### PR DESCRIPTION
**Pull request by abbaseya**
### Changes

- API route `PUT /api/v1/sites/goals` with form params `site_id`, `goal_type` and `goal_value` with supported types `event` and `page`
- API route `PUT /api/v1/sites/goals/:goal_id` with form params `site_id`, `goal_type` and `goal_value` with supported types `event` and `page`
- API route `DELETE /api/v1/sites/goals/:goal_id` with form param `site_id`

Documentation changes at PR [#149](https://github.com/plausible/docs/pull/149)

### Tests
- [x] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [x] Entry has been added to changelog
- [x] This PR does not make a user-facing change

### Documentation
- [x] [Docs](https://github.com/plausible/docs) have been updated
- [ ] This change does not need a documentation update

### CODE REVIEW

**Comment by ukutaht** [comment]
Thanks @abbaseya!

Definitely a worthwhile addition to the API. I'm happy to merge but the following points need to be addressed first:
* Automated tests
* Documentation for the endpoint
* Changelog entry

**Comment by abbaseya** [comment]
@ukutaht Thank you for your response. Changes pushed.

**Comment by ukutaht** [comment]
Thanks for the updates


What's the purpose of the `update` endpoint?

Personally I think it would be better to just use `delete` and `find_or_create` a new one if you want to change how a goal behaves. The update endpoint can also generate confusion. What happens if I take an existing custom even goal and pass update it with `{goal_type: 'page', goal_value: '...'}`?

The second point I wanted to bring up is that I think the `goal_value` parameter should be renamed to what it actually represents (given the different goal types). So to create a goal I would prefer this:

```json
{"goal_type": "event", "event_name": "Signup"}
{"goal_type": "page", "page_url": "/blabla"}
```

instead of

```json
{"goal_type": "event", "goal_value": "Signup"}
{"goal_type": "page", "goal_value": "/blabla"}
```

**Comment by abbaseya** [comment]
@ukutaht Well, your note on omitting the update endpoint actually makes more sense. Thanks for pointing that out.

As for the shape of the response. Just pushed an update that expects `event_name` or `page_path` instead of `goal_value` (_based on the `goal_type`_)

**Comment by ukutaht** [comment]
Thanks @abbaseya, looking good!

It just needed to be formatted which I've done in https://github.com/plausible/analytics/pull/1527. The code is now merged. I will deploy it onto our staging server for some testing and then it will be available on our hosted service next week.

**Pull request closed without merging**
