### PR TITLE
Referrer spam blocklist

### PR DESCRIPTION
**Pull request by RobertJoonas**
### Changes

Integrates with Matomo's [referrer spam list](https://github.com/matomo-org/referrer-spam-list) via https://github.com/plausible/referrer-blocklist. Automatic updates are included in the referrer-blocklist library.

### Tests
- [x] Automated tests have been added

### Changelog
- [ ] Entry has been added to changelog
- [ ] This PR does not make a user-facing change

### Documentation
- [x] This change does not need a documentation update

### Dark mode
- [x] This PR does not change the UI

### CODE REVIEW

**Comment by ukutaht** [comment]
Looks good to me :+1:  Nice job @RobertJoonas

**Comment by metmarkosaric** [comment]
Nice work @RobertJoonas! Looking forward to seeing this live! I'll update the docs to include a note about this

**Comment by ukutaht** [comment]
One thing @RobertJoonas this should be added to the Changelog. Feel free to commit straight on master.

**Comment by RobertJoonas** [comment]
Updated the changelog now too.

**Pull request merged**
