### PR TITLE
Update bamboo_postmark to fork repository

### LINKED ISSUE #1885: Account registration form issue with comma in the name
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

We've had couple of cases where Spanish people tried to register for a trial account and everything seemingly goes well but no email gets sent and the account is not actually registered in our database. In the Sentry errors, it seems like our registration form doesn't accept names with a comma (both of these cases had a comma in their names and removing the comma fixed the issue). I'm not sure if perhaps some other special characters are not supported either?

Would be nice if we either have a way to support these characters in the name field or perhaps easier that we give an error message for people so they know that the registration is not completed and that they can try entering their name without the comma.

### Expected behavior

Names with special characters should work too

### Screenshots

_No response_

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

### PR DESCRIPTION
**Pull request by vinibrsl**
This commit updates mix.exs to resolve bamboo_postmark to our fork. The fork encodes names with quotes when building e-mails, adding support for special names with commas and quotes. Related to plausible/bamboo_postmark#1.

Closes #1885

### CODE REVIEW

**Comment by ukutaht** [comment]
Looks good to me! One small request: Can you add a note to the fork readme that explains
a) That it's a fork of the original
b) Why we forked it

I've lost track of the _why_ on some of the forks I've done in the past. I think it's important to record it.

**Comment by spapas** [comment]
Hey friends, you've added the `{:bamboo_postmark, git: "https://github.com/plausible/bamboo_postmark.git", tag: "main"},` line in mix.exs but there's no main tag on that repo (actually there are no tags)... I had to remove the line to be able to get the deps on my system.

**Comment by vinibrsl** [comment]
> Hey friends, you've added the `{:bamboo_postmark, git: "https://github.com/plausible/bamboo_postmark.git", tag: "main"},` line in mix.exs but there's no main tag on that repo (actually there are no tags)... I had to remove the `tag` from there to be able to get the deps on my system.

Thanks for catching that! I meant `branch` instead of `tag`. Fixed in https://github.com/plausible/analytics/pull/2477/commits/991740ce04d333c4657fb483627ec4149910b0e6.

**Comment by vinibrsl** [comment]
> Looks good to me! One small request: Can you add a note to the fork readme that explains a) That it's a fork of the original b) Why we forked it
> 
> I've lost track of the _why_ on some of the forks I've done in the past. I think it's important to record it.

Good call! https://github.com/plausible/bamboo_postmark#fork

**Comment by aerosol** [comment]
Ref https://github.com/pablo-co/bamboo_postmark/issues/32

**Review by aerosol — APPROVED** [review]

**Review by ukutaht — APPROVED** [review]

**Pull request merged**
