### PR TITLE
OIDC

### PR DESCRIPTION
**Pull request by Kloenk**
This is based on #3705  and contains ideas from #3170 

### Changes
Add OIDC support for user creation and login

### Tests
- [ ] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog
- [ ] This PR does not make a user-facing change

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [ ] This change does not need a documentation update

### Dark mode
- [ ] The UI has been tested both in dark and light mode
- [x] This PR does not change the UI

### CODE REVIEW

**Comment by Kloenk** [comment]
the config `:plausible, Plausible.Auth.OIDC, site_membership_claim` can now be a function that accepts a claims map and returns a list of either strings or a tuple of 2 strings, the first being the domain, the second being the role in that domain.

**Comment by Kloenk** [comment]
As part is taken from another pr I'm not sure if I can fully grant this rights. Sorry for not seeing the cla before

**Comment by ukutaht** [comment]
@Kloenk Thank you for your contribution.

If I understand correctly, this PR will switch the login functionality for the whole Plausible application based on a config variable. This only makes sense in self-hosted / community edition for smaller teams since it treats Plausible as a single-tenant application.

The way I see it, we need to build [team/organization accounts](https://feedback.plausible.io/269) first and any sort of SSO features are a natural extension of that. Sadly this PR does not seem to fit into that story. Also sadly, team accounts isn't something we are tackling *just yet*. The plan is to work on this towards the end of this year.

**Comment by rmsc** [comment]
The team/organization accounts seems to be complete. Is now a good time to look into SSO?

IMHO, and in this day and age, I believe SSO is a must-have.

**Pull request closed without merging**
