### PR TITLE
Replace final image base to be alpine

### PR DESCRIPTION
**Pull request by BobyMCbobs**
# Goal

**_Currently work-in-progress._**

The final container image can be reduced by ~75% by replacing the base with alpine.

```
plausible/analytics                       bobymcbobs          4fb17172ceb0        10 minutes ago      57.5MB
plausible/analytics                       dev                 a7d58b5d74da        16 hours ago        242MB
```

The size of the container image is important as:
- in some environment there may not be a lot of storage
- nodes can run out of storage and cause problems
- if it can be reduced, it should be

### Changes

Please describe the changes made in the pull request here.

Below you'll find a checklist. For each item on the list, check one option and delete the other.

### Tests
- [ ] Automated tests have been added
- [x] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog
- [x] This PR does not make a user-facing change

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [x] This change does not need a documentation update

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
Currently getting the error:

```
/app/releases/0.0.1/../../erts-10.7.2.1/bin/erl: exec: line 12: /app/erts-10.7.2.1/bin/erlexec: not found
```

---

according to

```
/app # file erts-10.7.2.1/bin/erlexec
erts-10.7.2.1/bin/erlexec: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=ef464f52ec7d693c667eaaff8fc0b851e262ed70, with debug_info, not stripped
```

the binary is not statically linked, so it depends a bit on the system it was built on (being Debian).

**Comment by BobyMCbobs** [comment]
May or may not be related but at least with Erlang, it is possible to use _scratch_ (nothing) as the base image, so it can only contain the app and nothing OS related.

https://github.com/shortishly/erlang-in-docker-from-scratch

**Comment by ukutaht** [comment]
Awesome! I'd love to reduce the final image size

**Comment by BobyMCbobs** [comment]
In the latest commit, the image size has been further reduced:

```
plausible/analytics                       bobymcbobs          5f0b46b91d10        5 minutes ago       29.3MB
plausible/analytics                       dev                 3eade4a07b9c        9 minutes ago       242MB
plausible/analytics                       latest              edc04495bd46        20 hours ago        258MB
```

**Comment by BobyMCbobs** [comment]
Note:
- Alpine doesn't use GCC by default, but it has been included (build stage)
- for some reason the _ncurses_ package is required in at least the init stages
- some programs such as `adduser` have different syntax than Debian, see https://github.com/plausible/analytics/pull/353/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L67

**Comment by BobyMCbobs** [comment]
@ukutaht, this PR is ready! :smile: 
May I please have a review?

**Comment by ukutaht** [comment]
Looks good to me! Thanks a ton

**Pull request merged**
