### PR TITLE
add `v` prefix to version tags in public images

### PR DESCRIPTION
**Pull request by ruslandoga**
Cont. from https://github.com/plausible/analytics/discussions/2324#discussioncomment-3867370

[More info on `@metadata-action`'s semver](https://github.com/docker/metadata-action#typesemver)
[Demo workflow](https://github.com/ruslandoga/version-tag-test/blob/master/.github/workflows/build.yml)
[Result images](https://github.com/ruslandoga/version-tag-test/pkgs/container/version-tag-test)

```console
$ docker run -ti --rm ghcr.io/ruslandoga/version-tag-test:v1.5.0-rc.4 ash
$ cat meta.json | jq
{
  "tags": [
    "ghcr.io/ruslandoga/version-tag-test:v1.5.0-rc.4"
  ],
  "labels": {
    "org.opencontainers.image.title": "version-tag-test",
    "org.opencontainers.image.description": "",
    "org.opencontainers.image.url": "https://github.com/ruslandoga/version-tag-test",
    "org.opencontainers.image.source": "https://github.com/ruslandoga/version-tag-test",
    "org.opencontainers.image.version": "v1.5.0-rc.4",
    "org.opencontainers.image.created": "2022-10-17T05:23:39.594Z",
    "org.opencontainers.image.revision": "afcaa3d7ec07bbe060b96dd402ecb4b3797bdd1d",
    "org.opencontainers.image.licenses": ""
  }
}
```

### CODE REVIEW

**Review by paskal — APPROVED** [review]

**Comment by vinibrsl** [comment]
Could you please add this to the CHANGELOG file, @ruslandoga?

**Comment by ruslandoga** [comment]
@vinibrsl 👋

Sure, but what has changed? There haven't been any releases after `v1.4.0`, so nobody has been affected yet.

**Comment by ruslandoga** [comment]
Yes, the goal here to keep the tags format the same way as before :)

**Review by vinibrsl — APPROVED** [review]

**Comment by vinibrsl** [comment]
> Yes, the goal here to keep the tags format the same way as before :)
> 
> [#2324 (comment)](https://github.com/plausible/analytics/discussions/2324#discussioncomment-3867370)

Thanks for clarifying!

**Pull request merged**
