### PR TITLE
fix: truncate username on small screens

### LINKED ISSUE #784: Long username on mobile issue
"I found some minor issue with your responsive design b/c my surname is quite long. 🙈"

EviKTWUXcAAsmLW

([from twitter](https://twitter.com/NBvGersdorff/status/1366994557041332224))

### PR DESCRIPTION
**Pull request by niklaas**
### Changes

I've never contributed to a Phoenix application before. And my knowledge of Elixir is quite limited. I create this PR to show that I am keen to make this small contribution. I need further help:

The current stage of the proposed changes have the caveat that the suffix ' ...' is added to every (!) username. I would like to define a function that only truncates and adds the suffix if the username (or email address) is too long. Where in the codebase shall I implement that function and where do I `assign` the function to the view so I can use it in the template?

I am unsure whether to add tests or not. I haven't found an end-to-end test framework in your codebase yet. I there any? If not I'd say that the PR does not require tests.

fixes #784 

### Tests
- [ ] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [X] This change does not need a documentation update

### CODE REVIEW

**Comment by Vigasaurus** [comment]
My opinion (take what you will from it) - this could be done much more cleanly and with more widespread support for differing widths/trimming based on width as opposed to character count with a TailwindCSS setup using [truncate](https://tailwindcss.com/docs/text-overflow) as opposed to a generic phoenix template replacement.

**Comment by niklaas** [comment]
Didn't know about `truncate` from TailwindCSS. I'll implement it that way.

**Comment by ukutaht** [comment]
Agreed with @Vigasaurus. CSS has great support for truncation with ellipsis

**Comment by niklaas** [comment]
So this is a new attempt with CSS only. This is what it looks like:

Bildschirmfoto am 2021-03-26 um 18 59 55

Bildschirmfoto am 2021-03-26 um 19 00 02

This only works because all the other elements in the unordered list are hidden on small screen widths, see
https://github.com/niklaas/analytics/blob/5197d3b54f4326e560cbbc74e40585fc66bf5150/lib/plausible_web/templates/layout/app.html.eex#L32-L47.

**Comment by ukutaht** [comment]
Looks good @niklaas, thanks for this.

Mind fixing the conflict as well? I moved the header code from `app.html.eex` to `_header.html.eex` for better organization. The changes need to be done in the new file.

**Comment by niklaas** [comment]
You're welcome, I'll fix the conflict within the next days.

**Comment by niklaas** [comment]
I have just fixed the conflicts an re-applied my changes. I tested it locally and it works the same way as shown in the comment above.

**Comment by ukutaht** [comment]
Amazing, thanks!

**Pull request merged**
