### PR TITLE
Decorate site settings sidebar with heroicons

### PR DESCRIPTION
**Pull request by aerosol**
### Changes

image

image

### Tests
- [ ] Automated tests have been added
- [x] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog
- [x] This PR does not make a user-facing change

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [x] This change does not need a documentation update

### Dark mode
- [x] The UI has been tested both in dark and light mode
- [ ] This PR does not change the UI

### CODE REVIEW

**Review by macobo — APPROVED** [review]
Tested it, looks great! 

If I had to nitpick, the goals icon seems kind of ambigious and eye-like next the visibility settings. 
image

**Comment by aerosol** [comment]
> Tested it, looks great!
> 
> If I had to nitpick, the goals icon seems kind of ambigious and eye-like next the visibility settings. image

Open to suggestions: https://heroicons.com/ - there's no soccer icons unfortunately 😅

**Comment by macobo** [comment]
Not sure either. Something like this might be more ideal, but not in heroicons:

image


Some ideas from browsing their site:

- trophy: image
- fire: image
- cursor-arrow-ripple: image
- presentation-chart-line: image

I think I like trophy the most out of these:

image

**Comment by aerosol** [comment]
@ukutaht WYT? ^^

**Pull request merged**
