### PR TITLE
Make new tab dashboard links work

### PR DESCRIPTION
**Pull request by aerosol**
I have no idea what I'm doing wrt react router, but this seems to work?

### CODE REVIEW

**Comment by ukutaht** [comment]
Ah, nice find with the `basename` prop. Seems to fix the linking issues indeed 👍

For shared links this should work: https://github.com/plausible/analytics/commit/3ba5a3c28547bbd5f7afbcdd6d5c9cc8ebb06006

**Comment by aerosol** [comment]
There's still some discrepancy between staging/preview and localhost. On localhost I'm getting duplicated domain fragment on left-clicks:

image

**Comment by aerosol** [comment]
@ukutaht how about 7190e7e?

**Comment by ukutaht** [comment]
> @ukutaht how about [7190e7e](https://github.com/plausible/analytics/commit/7190e7e10e9063af8dec9e3754e5a40492c74354)?

Much better 👌

**Pull request merged**
