### PR TITLE
Fix: Re-add hash and outbound-links only options

### PR DESCRIPTION
**Pull request by jonnitto**
### Changes

Please describe the changes made in the pull request here.

Below you'll find a checklist. For each item on the list, check one option and delete the other.

### Tests
- [x] This PR does not require tests

### Changelog
- [x] This PR does not make a user-facing change

### Documentation
- [x] This change does not need a documentation update

### CODE REVIEW

**Comment by jonnitto** [comment]
`hash` and `outbound-links` only option, was removed here:

https://github.com/plausible/analytics/commit/fb7a3fef896b2e87eacd829399958450adfb3785#diff-4937d77a31579beff9907cd9e7f57d322bb765e6f55c5934641d50ddbdfcac19

**Comment by Vigasaurus** [comment]
Huh, I dunno how I did that/didn't notice, heh

**Comment by metmarkosaric** [comment]
thanks @jonnitto! appreciate your help!

**Comment by jonnitto** [comment]
It was a pleasure!

**Comment by jonnitto** [comment]
I think it would be good to add also all the variants of scripts to a monitor system. Wdyt?

**Comment by ukutaht** [comment]
@jonnitto Makes sense I will add it to our uptime monitoring

**Pull request merged**
