### PR TITLE
Additional pre-commit hooks

### PR DESCRIPTION
**Pull request by janosh**
### Changes

Add the following language agnostic 1st party pre-commit hooks and apply them to all files via `pre-commit run -av`:

```yml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: priv/tracker/js
      - id: mixed-line-ending
      - id: trailing-whitespace
```

### Tests
- [x] This PR does not require tests

### Changelog
- [x] This PR does not make a user-facing change

### Documentation
- [x] This change does not need a documentation update

### CODE REVIEW

**Comment by ukutaht** [comment]
Thanks!

**Comment by ukutaht** [comment]
Hey, could you revert the latest commit? It is fixed in another PR: https://github.com/plausible/analytics/pull/1427/commits/44c12c530a980fc32d6d7d177e177a4e27e52ba7

**Comment by janosh** [comment]
@ukutaht Certainly, last commit is reverted.

**Comment by ukutaht** [comment]
Could you also exclude `priv/ref_inspector` and `priv/ua_inspector` yaml files from this? These are downloaded from an external source and not maintained by us

**Comment by janosh** [comment]
Done.

**Pull request merged**
